#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/down.jpg
fi

leftwm-command "UnloadTheme"

pkill compton
pkill picom
pkill polybar
pkill dunst
pkill protonmail-bridge
pkill birdtray
pkill ipfs
pkill nextcloud
pkill volumeicon
